version: "2"
services:
  common:
    tty: true
    stdin_open: true
    image: base
    volumes:
      - ../../../:/altcoin
  manager:
    hostname: manager
    entrypoint: sh -c '/altcoin/virtual_world/docker/dev/run.node.sh; bash'
    extends: common
    networks:
      altcoin_net:
        ipv4_address: 10.0.0.10
  altcoin0_a:
    hostname: altcoin0
    entrypoint: sh -c '/altcoin/virtual_world/docker/dev/run.node.sh; bash'
    extends: common
    networks:
      altcoin_net:
        ipv4_address: 10.0.1.10
    links:
      - manager
  altcoin1_a:
    hostname: altcoin1
    entrypoint: sh -c '/altcoin/virtual_world/docker/dev/run.node.sh; bash'
    extends: common
    networks:
      altcoin_net:
        ipv4_address: 10.0.1.20
    links:
      - manager
networks:
  altcoin_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/16
